
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r apps/orchestrator/requirements.txt
          pip install pytest
      - name: Run tests
        env:
          PYTHONPATH: apps/orchestrator
        run: pytest -q

